name: Integration Test
on: [push , pull_request]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
      
      
      # Deploy model in Azure Machine Learning to AKS
      - name: Deploy model to AKS
        id: aml_deploy_aks
        uses: ./
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
            model_name:  mymodel
            model_version: 1
            parameters_file: "test/test_aks_deploy.json"
